%Design and Analysis of Launch Vehicle and Trajectory

%Computing and analyzing total energy loss due to gravity and drag in a ascent mission by varying burn rate of the propellent

m_0     = 80000;        %kg; total mass of the rocket
m_p     = 60000;        %kg; mass of the propellent
m_b     = m_0 - m_p;    %kg; burnout mass of the rocket
g_0     = 9.81;         %m/s^2; acceleration due to gravity at sea level
I_sp    = 300;          %sec; specific impulse of the rocket engine
ppf     = m_p/m_0;      %propellent fraction
beta    = (300:1:1600); %kg/s; burn rate of the propellent
rho     = 0.225;        %kg/m^3; averaged desnity at the terminal altitude
S_ref   = pi;           %m^2; Net surface area of the bluff body
c_d_0   = 1;            %drag coefficient of the body

%Calculating ideal burnout velocity of the rocket (m/s)
v_ideal = I_sp*g_0*log(m_0/m_b);

%Ideal energy generated by the rocket at terminal performance (J)
e_ideal = 0.5*(v_ideal)^2;

%Maximum possible terminal burnout velocity under the effect of gravity (m/s)
v_g     = v_ideal - g_0*(ppf*m_0./beta);

%Calculating total drag produced at the terminal end of the trajectory (N)
D       = 0.5*rho.*((v_g).^2)*S_ref*c_d_0;

%Deceleration on the rocket body at the terminal altitude (m/s^2)
a_D     = D/m_b;

%Average decelaration on the rocket body (m/s^2)
a_avg   = a_D/2;

%Maximum possible terminal burnout velocity under the effect of drag and gravity (m/s)
v_D     = v_g - a_avg.*(ppf*m_0./beta);

%Terminal altitude of the rocket achieved under the gravity (m)
h_g     = (((m_0*I_sp*g_0)./beta)*((1-ppf)*log(1-ppf)+ppf))-(0.5*g_0.*(ppf*m_0./beta).^2);

%Terminal altitude of the rocket achieved under the drag and gravity (m)
h_D     = h_g - (0.5*a_avg.*(ppf*m_0./beta).^2);

%Combined loss of energy due to drag and gravity (J)
delta_e = 0.5.*(v_ideal).^2 - 0.5.*(v_D).^2 - g_0.*h_D;

%Percentage change in total energy due to drag and gravity
e_per   = ((delta_e/e_ideal)*100);

plot(beta,e_per)
grid on
title('Variation in Loss of Energy (delta_e) due to change in burn rate of the propellent (beta)')
xlabel('Burn Rate of Propellent (kg/s)')
ylabel('Percentage change in energy loss due to gravity (%)')